---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# [1.변수]
# 변수명 .x가능, .1불가능

# <-과 =의 차이
#   * =는 최상위 수준에서만 사용가능
#   * <-는 어느곳에서든 사용 가능


# [2.함수호출 시 인자 지정]
# 함수 foo(a, b, c=1, d=2)
# foo(3, 4) -> a=3, b=4, c=1, d=2
# foo(3, 4, 1) -> a=3, b=4, c=1, d=2
# foo(3, 4, 5) -> a=3, b=4, c=5, d=2
# foo(d=5, a=3, b=4) -> a=3, b=4, c=1, d=5


# [3.스칼라]
# NA와 NULL의 차이
#   * NA는 결측치(값입력X, 관찰X, 적절한항목에 적절한값X)
#   * NULL는 변수값이 아직 미정인 상태 표현
```{r}
is_even <- NULL
if (is_even %% 2 == 0) {
  is_even <- TRUE
} else {
  is_even <- FALSE
}
```

# 진리값
```{r}
# &: 백터간 계산
c(TRUE, TRUE) & c(TRUE, FALSE)  # TRUE FALSE
# &&: 두개의 진리값끼리 연산하기 위함
c(TRUE, TRUE) && c(TRUE, TRUE)  # TRUE

```

# 팩터
```{r}
# 범주형 데이터를 표현하기 위함
# 범주형 데이터 = 사전에 정해진 특정 유형으로만 분류되는 경우(관측값+level)
# 범주형데이터(명목형, 순서형) <-> 수치형 데이터

# [범주형데이터]
# 1.팩터값 생성: factor(x, levels, ordered)
# level 생략 -> 데이터로부터 자동으로 파악
sex <- factor("m", c("m", "f"))  # ordered: TRUE=순서형, FALSE=명목형, 기본값=FALSE
sex

# 2.레벨 개수 반환: nlevels(x)
nlevels(sex)

# 3.레벨의 목록반환: levels(x)
levels(sex)
# 3-1.레벨 직접 수정
levels(sex) <- c("male", "female")

# 4.펙터인지 판단: is.factor(x)
is.factor(sex)

# [순서형데이터]
# 5.순서형 팩터 생성: ordered(x)
# factor(x, levels, ordered=TRUE)
ordered("a", c("a", "b", "c"))  # levels: a < b < c

# 6.순서형 팩터인지 확인: is.ordered(x)
```
# 벡터
```{r}
# 1.백터 생성
x <- c(1, 3, 4)

# 2.객체 이름 반환
names(x) <- c("kim", "seo", "park")

# 3.객체에 이름 저장
names <- ()

# 다른 타입이면 형변환
# NULL < raw < logical < integer < double < complex < character < list < expression

# 백터는 중첩될 수 없다
c(1, 2, 3, c(1, 2, 3))  # 1 2 3 1 2 3


# 
# 
# 
# 
```

```{r}
x1 <- c("a", "b", "c")
length(x1)  # 3
nrow(x1)    # NULL(행렬만 가능)
NROW(x1)    # 3   (벡터와 행렬 모두 가능)
```

```{r}
xx <- c(1, 2, 3)
yy <- c(1, 3, 4)

# 1.동일한지 판단 : 하나의 결과
identical(xx, yy)

# 2.합집합 구하기
union(xx, yy)

# 3.교집합 구하기
intersect(xx, yy)

# 4.차집합 구하기
setdiff(xx, yy)

# 5.같은 집합인지 확인
setequal(xx, yy)
setequal(c("a", "b", "c"), c("a", "d"))
setequal(c("a", "b", "c"), c("a", "b", "c", "c"))  # TRUE
identical(c("a", "b", "c"), c("a", "b", "c", "c"))  # FALSE


# 6.포함여부확인
"d" %in% xx

# 7.연산자
x <- c(1, 2, 3, 4, 5)
10 - x
```

```{r}
# 시퀀스 생성
seq(from, to, by)  # by=증가치
seq(7:3)  # 7 6 5 4 3
seq(3, 7, 3)  # 3 6
3:7  # 3 4 5 6 7

# 주어진 객체의 길이만큼 시퀀스 생성
# seq_along(along.with = )
x <- c(2, 4, 6, 8, 10)
1:NROW(x)     # [1] 1 2 3 4 5
seq_along(x)  # [1] 1 2 3 4 5

```

```{r}
# 반복된 값 저장
rep(1:2, times = 5)           # [1] 1 2 1 2 1 2 1 2 1 2
rep(1:2, each = 5)            # [1] 1 1 1 1 1 2 2 2 2 2
rep(1:2, each = 5, times = 2) # [1] 1 1 1 1 1 2 2 2 2 2 1 1 1 1 1 2 2 2 2 2
```

# 리스트
#  - (키, 값)형태의 데이터
#  - 서로 다른 타입의 데이터 넣을 수 있음
```{r}
x <- list(name = "foo", height = c(1, 3, 5))
x$name  # "foo"
x[1]    # (name, "foo")
x[[1]]  # "foo"
x[2]    # (height, c(1, 3, 5))
x[[2]]  # 1 3 5

# 중첩 가능
list(a = list(val = c(1, 2, 3)), b = list(val = c(1, 2, 3, 4)))
```

# 행렬
```{r}
# 1.행렬 생성
matrix(data = , nrow = , ncol = , byrow = FALSE, dimnames = NULL)
# byrow=T:행우선, byrow=F:열우선 / dimnames:행렬의 각 차원에 부여할 이름

# 2.객체의 차원에 이름 설정
dimnames(x) <- values

# 3.행/열이름 가져오기
rownames(x) / colnames(x)

# 4.행/열이름 설정
rownames(x) <- values
colnames(x) <- values
```

```{r}
# 1.전치행렬
t(
  x # 행렬 / 데이터 프레임
)

# 2.수식 a%*%x = b에서 x를 구한다
solve(
  a,  # 행렬
  b   # 행렬 / 벡터
)

# 3.배열의 행/열의 수
nrow / ncol(
  x   # 벡터, 배열, 데이터프레임
)

# 4.객체의 차원수
dim(
  x  # 행렬, 배열, 데이터프레임
)

# 5.객체의 차원 수 지정
dim(
  x  # 행렬, 배열, 데이터프레임
) <- value  # 객체의 차원
```

```{r}
matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3)  # byrow=FALSE
#      [,1] [,2] [,3]
# [1,]    1    4    7
# [2,]    2    5    8
# [3,]    3    6    9

x <- matrix(1:9, nrow=3, ncol=3,dimnames = list(c("r1", "r2", "r3"), c("c1", "c2", "c3")))
#    c1 c2 c3
# r1  1  4  7
# r2  2  5  8
# r3  3  6  9

colnames(x) <- c("col1", "col2", "col3")  # 이때 matrix 만들 때 nrow, ncol지정해줘야한다. 아니면 에러남
x
#    col1 col2 col3
# r1    1    4    7
# r2    2    5    8
# r3    3    6    9
```

```{r}
# 스칼라 x 곱하기
A * x

# 행렬 곱하기
A %*% B
```

```{r}
mat <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3)

# 전치행렬
t(mat)
#      [,1] [,2] [,3]          [,1] [,2] [,3]
# [1,]    1    4    7     [1,]    1    2    3
# [2,]    2    5    8     [2,]    4    5    6
# [3,]    3    6    9     [3,]    7    8    9

# 역행렬
A = (a, b
     c, d)
A의 역행렬 = 1/(ad-bc)( d, -b
                       -c,  a)

# 차원 확인 및 변경
matt <- matrix(c(1, 2, 3, 4, 5, 6), ncol = 3)
dim(matt)  # 2 3
dim(matt) <- c(3, 2)
matt
#      [,1] [,2] [,3]            [,1] [,2]
# [1,]    1    3    5       [1,]    1    4
# [2,]    2    4    6       [2,]    2    5
#                           [3,]    3    6
```

# 배열
```{r}
# 3 x 4배열
array(1:12, dim = c(3, 4))
#      [,1] [,2] [,3] [,4]
# [1,]    1    4    7   10
# [2,]    2    5    8   11
# [3,]    3    6    9   12

# 2 x 2 x 3배열
array(1:12, dim = c(2, 2, 3))
# , , 1
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4
# 
# , , 2
#      [,1] [,2]
# [1,]    5    7
# [2,]    6    8
# 
# , , 3
#      [,1] [,2]
# [1,]    9   11
# [2,]   10   12
```

# 데이터 프레임
```{r}
# 엑셀의 스프레드시트라고 생각
d <- data.frame(x = c(1, 2, 3, 4, 5),
                y = c(2, 4, 6, 8, 10),
                z = c("M", "F", "M", "F", "M"))
str(d)
```

```{r}
data_frame1 <- data.frame(x = c(1, 2, 3, 4, 5),
                          y = c(2, 4, 6, 8, 10))

data_frame1[-1, -2]  # 2 3 4 5
result1 <- data_frame1[, c("x"), drop=FALSE]  # 데이터프레임 반환
result2 <- data_frame1[, c("x")]  # 기본: drop=TRUE -> 형변환
```

```{r}
data_frame2 <- data.frame(a=1:3, b=4:6, c=7:9)

d[, names(d) %in% c("b", "c")]
#    b  c
# 1  4  7
# 2  5  8
# 3  6  9

d[, !names(d) %in% c("b", "c")]
#    b  c
# 1  4  7
# 2  5  8
# 3  6  9
```
