---
title: "2_일표본 검정"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tidyverse")
install.packages("plotly")
install.packages("ggplot2")
install.packages("psych")
install.packages("lawstat")
install.packages("agricolae")
install.packages("DescTools")
```

```{r}
library(tidyverse)
library(plotly)
library(ggplot2)
library(psych)
library(lawstat)
library(agricolae)
library(DescTools)
```

# <가설>
# 귀무가설 : (모집단, 모평균에 대한) 기존의 입장 (-> 영가설)
# 대립가설 : (모집단, 모평균에 대한) 새로운 입장

#                               결정
#               귀무(참)                    대립(참)
# 사실  귀무(참)    ok                     error(제1종오류(알파))
#       대립(참)  error(제2종오류(베타))       ok
# ** 알파와 베타는 반비례!(알파가 더 중요)

# 가정: 1) 모집단=정규분포, 2) 표편=시그마=10
# Ho: M = 170
# H1: M > 170
# 귀무가설이 맞다면, 표본평균의 분포(X바)는 모집단이 정규분포면 
# 표본평균의 분포는 무조건 정규분포 
# Ho: X바 ~ N(M=170, 루트n분에 시그마)
# H1: X바 ~ N(M>170, 루트n분에 시그마)

# 표준화 -> (X - 평균) / 표준편차 -> Z = (X - M) / 시그마 ~ N(0, 1^2)=표준정규분포
# X바 ~ N(M=170, 루트n분에 시그마) -> Z = (X바 - M) / 루트n분에 시그마 ~ N(0, 1^2)

# <R을 이용한 윌콕슨의 부호 순위 검정>
# X    25          16          44  82  36  58  18
# Y    (25-35)-10  (16-35)-19  9   47  1   23  -17
# |Y|  10          19          9   47  1   23   17
# 순위 3           5           2   7   1   6    4
# W+(부호가 +인 것의 순위를 더해준다) 2+7+1+6=16
# W+ ~ W(알파, n) -> W+ -> Zw+ = (W+ - 평균) / W+의 표준편차 ~ N(0, 1^2)
```{r}
# 윌콕슨의 부호순위 검정
# 일표본 검정에서 모집단의 분포가 정규성이 깨졌을 때에 하는 비모수적 방법

# 귀무가설: 한국 성인들의 한달 평균 용돈은 35만원이다.
# 대립가설: 한국 성인들의 한달 평균 용돈은 35만원보다 많다.
# wilcox.test(data$variable, mu = , alternative = )
# mu: 귀무가설이 참일때의 모평균 
# alternative: 대립가설("greater", "less", "two.sided")
money <- c(25, 16, 44, 82, 36, 58, 18)
wilcox.test(money, mu = 35, alternative = "greater")
# W+ = V = 16 ==> Zw+ = Zv ~ N(0, 1) ==> 유의확률 0.406 -> 상위 40.6%
# 상위40.6% -> 상위5%안에 들지 않기 때문에 귀무가설 채택

# 결론: 유의확률이 0.406이므로 유의수준 0.05에서 한국 성인들의 한달용돈에는
#       통계적으로 유의한 변화는 없는것으로 나타났다. 귀무가설을 채택한다.
```

# <R을 이용한 일표본 검정>
```{r}
# 정규성 검정
# 귀무가설: 정규분포를 따른다.
# 대립가설: 정규분포를 따르지 않는다.

# Shapiro-Wilk Normality Test
# shapiro.test(data$variable)

# 예제 데이터: attitude
# 변수: 7개
# 양적자료
a <- shapiro.test(attitude$rating)
str(a)
a$p.value
# 결론: 유의확률이 0.255이므로 유의수준 0.05에서 귀무가설 채택->정규성가정 만족

Variables <- c()
Method <- c()
Statistics <- c()
PValues <- c()

# rbind -> rbind(a, b) -> a
#                         b
# cbind -> cbind(a, b) -> a b
str(attitude)  # 30개 데이터, 7개열

for(i in 1:7){
  result <- list()
  if(shapiro.test(attitude[ , i])$p.value >= 0.05){
    result <- t.test(attitude[, i], mu = 50, alternative = "greater")
  }else{
    result <- wilcox.test(attitude[, i], mu = 50, alternative = "greater")
  }
  
  Variables <- rbind(Variables, colnames(attitude)[i])
  Method <- rbind(Method, result$method)
  # round(data$variable, digits = n) 소수점 n자리로 만들기
  Statistics <- rbind(Statistics, round(result$statistic, digits = 3))
  PValues <- rbind(PValues, round(result$p.value))
}

Variables
#      [,1]        
# [1,] "rating"    
# [2,] "complaints"
# [3,] "privileges"
# [4,] "learning"  
# [5,] "raises"    
# [6,] "critical"  
# [7,] "advance" 

Method
#      [,1]                                                  
# [1,] "One Sample t-test"                                   
# [2,] "One Sample t-test"                                   
# [3,] "One Sample t-test"                                   
# [4,] "One Sample t-test"                                   
# [5,] "One Sample t-test"                                   
# [6,] "Wilcoxon signed rank test with continuity correction"
# [7,] "One Sample t-test"

Statistics
#               t
# [1,]   6.584486
# [2,]   6.828660
# [3,]   1.402646
# [4,]   2.971086
# [5,]   7.708794
# [6,] 464.000000
# [7,]  -3.761963
              
PValues
#              [,1]
# [1,] 1.624343e-07
# [2,] 8.439166e-08
# [3,] 8.566895e-02
# [4,] 2.954914e-03
# [5,] 8.415196e-09
# [6,] 9.981378e-07
# [7,] 9.996198e-01

one.sample.test <- data.frame(Variables, Method, Statistics, PValues)
writexl::write_xlsx(one.sample.test, path = "d:/one_sample_test.xlsx")
```

# R을 이용한 일표본 검정에 대한 Flow Chart
```{r}
# 일표본 검정

# 정규성 검정(다이아몬드) --No--> Wilcoxon's signed rank test
# [shapiro.test(data$variable)]   [wilcox.test(data$variable, mu=, alternative= )]
#         |
#        yes
#         |
#    one sample t-test
# [t.test(data$variable, mu=, alternative=)]
```
