---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 웹 스크레이핑 방법
```{r}
# 1. 대상 설정: URL 할당
# 2. 웹문서 추출: htmlParse()
# 3. 특정태그의 Data 추출: xpathSApply()
# 4. 데이터 정제(특수문자, 공백문제 제거)
#         : gsub('\n', '', name) - name에서 '\n'을 제거하겠다는 명령어
# 5. 데이터프레임
# 6. 정렬
```

```{r}
install.packages("XML")
```

```{r}
library(XML)
```

```{r}
url <- "https://www.coupang.com/np/categories/498829?listSize=60&brand=&offerCondition=&filterType=&isPriceRange=false&minPrice=&maxPrice=&page=1&channel=user&fromComponent=Y&selectedPlpKeepFilter=&sorter=bestAsc&filter=&component=498729&rating=0"
doc <- htmlParse(url, encoding = "UTF-8")

# //는 중간단계를 건너 뛴다.
prodName <- xpathSApply(doc, "//ul[@id='productList']//div[@class='name']", xmlValue)
# "\n   루넨\n"으로 나옴

# 가방 이름만 가지고오겠다!
prodName <- gsub('\n', '', prodName)
prodName <- gsub(' ', '', prodName)
prodName

price <- xpathSApply(doc, "//ul[@id='productList']//strong[@class='price-value']")
```

```{r}
df <- data.frame(상품명=prodName, 가격=price)

df$상품명 <- format(df$상품명, justify="left")
```